### ISSUE TITLE
bug with submodule procedures w/ contains

### ISSUE THREAD

**Issue by porteri** [Fortran-FOSS-Programmers/ford#245]
It looks like Ford doesn't know how to handle a submodule procedure that has a contains statement in it:
```
1>Exception: CONTAINS statement in SUBMODULEPROCEDURE
```

**Comment by rouson** [comment]
I'm adding the following transcript to demonstrate a minimal reproducible example:
```
> ls
foo-module.f90		internal-subprogram.md

> cat internal-subprogram.md 
project: internal subprogram issue
src_dir: .

> cat foo-module.f90 
module foo_module
  interface
    module subroutine foo()
    end subroutine
  end interface
end module

submodule(foo_module) foo_submodule
contains
  module procedure foo
  contains
    subroutine bar()
    end subroutine
  end procedure
end submodule

> ford internal-subprogram.md 
Reading file foo-module.f90
Traceback (most recent call last):
  File "/usr/local/bin/ford", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/ford/__init__.py", line 391, in run
    main(proj_data,proj_docs,md)
  File "/usr/local/lib/python3.7/site-packages/ford/__init__.py", line 342, in main
    project = ford.fortran_project.Project(proj_data)
  File "/usr/local/lib/python3.7/site-packages/ford/fortran_project.py", line 90, in __init__
    ford.sourceform.FortranSourceFile(os.path.join(curdir,item),settings, preprocessor, ext in self.fixed_extensions,incl_src=html_incl_src))
  File "/usr/local/lib/python3.7/site-packages/ford/sourceform.py", line 1052, in __init__
    FortranContainer.__init__(self,source,"")
  File "/usr/local/lib/python3.7/site-packages/ford/sourceform.py", line 654, in __init__
    self.SUBMODULE_RE.match(line),self))
  File "/usr/local/lib/python3.7/site-packages/ford/sourceform.py", line 630, in __init__
    permission))
  File "/usr/local/lib/python3.7/site-packages/ford/sourceform.py", line 560, in __init__
    raise Exception("CONTAINS statement in {}".format(type(self).__name__[7:].upper()))
Exception: CONTAINS statement in SUBMODULEPROCEDURE
> ford --version
FORD, version 6.0.0
> 
```
