### ISSUE TITLE
v6.0.0 regression

### ISSUE THREAD

**Issue by alinelena** [Fortran-FOSS-Programmers/ford#246]
I have a project that builds fine in 5.0.6 but fails in 6.0.0

this is on an included file with fortran include. I will try to make a reproducer asap. The error is below just in case.

```
Traceback (most recent call last):
  File "/opt/ford/6.0.0/bin/ford", line 11, in <module>
    load_entry_point('FORD==6.0.0', 'console_scripts', 'ford')()
  File "/opt/ford/6.0.0/lib/python3.6/site-packages/FORD-6.0.0-py3.6.egg/ford/__init__.py", line 391, in run
    main(proj_data,proj_docs,md)
  File "/opt/ford/6.0.0/lib/python3.6/site-packages/FORD-6.0.0-py3.6.egg/ford/__init__.py", line 342, in main
    project = ford.fortran_project.Project(proj_data)
  File "/opt/ford/6.0.0/lib/python3.6/site-packages/FORD-6.0.0-py3.6.egg/ford/fortran_project.py", line 90, in __init__
    ford.sourceform.FortranSourceFile(os.path.join(curdir,item),settings, preprocessor, ext in self.fixed_extensions,incl_src=html_incl_src))
  File "/opt/ford/6.0.0/lib/python3.6/site-packages/FORD-6.0.0-py3.6.egg/ford/sourceform.py", line 1052, in __init__
    FortranContainer.__init__(self,source,"")
  File "/opt/ford/6.0.0/lib/python3.6/site-packages/FORD-6.0.0-py3.6.egg/ford/sourceform.py", line 789, in __init__
    raise ("Found procedure call in {}".format(type(self).__name__[7:].upper()))
TypeError: exceptions must derive from BaseException
make[3]: *** [CMakeFiles/ford.dir/build.make:57: CMakeFiles/ford] Error 1
make[2]: *** [CMakeFiles/Makefile2:73: CMakeFiles/ford.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/ford.dir/rule] Error 2
make: *** [Makefile:164: ford] Error 2
```

**Comment by ZedThree** [comment]
This was fixed in b1b3c04
