### ISSUE TITLE
Doublecomplex is not recognized

### ISSUE THREAD

**Issue by PaulXiCao** [Fortran-FOSS-Programmers/ford#251]
The data type doublecomplex is not recognized.

**Comment by kevung** [comment]
Hello, as an bug example, this function:
`      double complex function conjugate(z)
         implicit none
         double complex z
         conjugate=dconjg(z)
      end function
`
gives this error
Reading file conj.f
Traceback (most recent call last):
  File "/usr/bin/ford", line 11, in <module>
    load_entry_point('FORD==6.0.0', 'console_scripts', 'ford')()
  File "/usr/lib/python3.7/site-packages/ford/__init__.py", line 391, in run
    main(proj_data,proj_docs,md)
  File "/usr/lib/python3.7/site-packages/ford/__init__.py", line 342, in main
    project = ford.fortran_project.Project(proj_data)
  File "/usr/lib/python3.7/site-packages/ford/fortran_project.py", line 90, in __init__
    ford.sourceform.FortranSourceFile(os.path.join(curdir,item),settings, preprocessor, ext in self.fixed_extensions,incl_src=html_incl_src))
  File "/usr/lib/python3.7/site-packages/ford/sourceform.py", line 1052, in __init__
    FortranContainer.__init__(self,source,"")
  File "/usr/lib/python3.7/site-packages/ford/sourceform.py", line 681, in __init__
    permission))
  File "/usr/lib/python3.7/site-packages/ford/sourceform.py", line 523, in __init__
    strings)
  File "/usr/lib/python3.7/site-packages/ford/sourceform.py", line 186, in __init__
    self._initialize(first_line)
  File "/usr/lib/python3.7/site-packages/ford/sourceform.py", line 1345, in _initialize
    rettype, retkind, retlen, retproto, rest =  parse_type(attribstr,self.strings,self.settings)
  File "/usr/lib/python3.7/site-packages/ford/sourceform.py", line 2305, in parse_type
    if not match: raise Exception("Invalid variable declaration: {}".format(string))
Exception: Invalid variable declaration: doublecomplex

but this function is correctly parsed:
`      function conjugate(z)
         implicit none
         double complex conjugate
         double complex z
         conjugate=dconjg(z)
      end function

`

**Comment by ZedThree** [comment]
Fixed in #252
