### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by pgierz** [Fortran-FOSS-Programmers/ford#270]
Dear colleagues,

I get the following error when trying to use ford. Is this a problem related to my Fortran program, or is there a bug in the python code?

Cheers,
Paul

```
Traceback (most recent call last):
  File "/home/ollie/pgierz/.local/bin/ford", line 10, in <module>
    sys.exit(run())
  File "/home/ollie/pgierz/.local/lib/python3.6/site-packages/ford/__init__.py", line 391, in run
    main(proj_data,proj_docs,md)
  File "/home/ollie/pgierz/.local/lib/python3.6/site-packages/ford/__init__.py", line 342, in main
    project = ford.fortran_project.Project(proj_data)
  File "/home/ollie/pgierz/.local/lib/python3.6/site-packages/ford/fortran_project.py", line 115, in __init__
    self.extra_files.append(ford.sourceform.GenericSource(os.path.join(curdir,item),settings))
  File "/home/ollie/pgierz/.local/lib/python3.6/site-packages/ford/sourceform.py", line 2119, in __init__
    self.raw_src = r.read()
  File "/global/AWIsoft/intel/2019/intelpython3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 6319: invalid start byte
```

**Comment by wadudmiah** [comment]
I think this is related to non-UTF-8 characters in your source code. I'm wondering if FORD will support other character encodings in the future?

**Comment by zbeekman** [comment]
If possible, could someone please test drive the changes in PR #263? I think this will fix your issue.

**Comment by ZedThree** [comment]
#263 now allows you to set `encoding: <encoding>` in your project settings for non-UTF-8 encoded files

**Comment by jamaa** [comment]
> #263 now allows you to set `encoding: <encoding>` in your project settings for non-UTF-8 encoded files

finally found this option while searching through the issues. This should really be documented in https://github.com/Fortran-FOSS-Programmers/ford/wiki/Project-File-Options
