### ISSUE TITLE
Bug when fortran program does not begin with 'program': Found variable in SOURCEFILE

### ISSUE THREAD

**Issue by kevung** [Fortran-FOSS-Programmers/ford#271]
The following fortran program main.f compiles correctly
```
      IMPLICIT NONE
      integer toto
      end program

```
but gives this Ford bug:
```
Traceback (most recent call last):
  File "/usr/bin/ford", line 11, in <module>
    load_entry_point('FORD==6.0.0', 'console_scripts', 'ford')()
  File "/usr/lib/python3.7/site-packages/ford/__init__.py", line 391, in run
    main(proj_data,proj_docs,md)
  File "/usr/lib/python3.7/site-packages/ford/__init__.py", line 342, in main
    project = ford.fortran_project.Project(proj_data)
  File "/usr/lib/python3.7/site-packages/ford/fortran_project.py", line 90, in __init__
    ford.sourceform.FortranSourceFile(os.path.join(curdir,item),settings, preprocessor, ext in self.fixed_extensions,incl_src=html_incl_src))
  File "/usr/lib/python3.7/site-packages/ford/sourceform.py", line 1052, in __init__
    FortranContainer.__init__(self,source,"")
  File "/usr/lib/python3.7/site-packages/ford/sourceform.py", line 759, in __init__
    raise Exception("Found variable in {}".format(type(self).__name__[7:].upper()))
Exception: Found variable in SOURCEFILE

```
This corrected version does not give the bug:
```
      program
      IMPLICIT NONE
      integer toto
      end program

```

**Comment by zbeekman** [comment]
FORD aims to be an opinionated documentation generator. It's not meant to be a general purpose Fortran parser/linter. As such I think I'm going to mark this as "Won't fix".
