### ISSUE TITLE
Bad escape crash

### ISSUE THREAD

**Issue by jacobwilliams** [Fortran-FOSS-Programmers/ford#296]
I think #136 (or similar) is happening again.

I get a crash if there are strings in the code with `\` characters:

```
Traceback (most recent call last):
  File "\anaconda3\lib\sre_parse.py", line 1021, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\O'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "\anaconda3\Scripts\ford.exe\__main__.py", line 9, in <module>
  File "\anaconda3\lib\site-packages\ford\__init__.py", line 391, in run
    main(proj_data,proj_docs,md)
  File "\anaconda3\lib\site-packages\ford\__init__.py", line 342, in main
    project = ford.fortran_project.Project(proj_data)
  File "\anaconda3\lib\site-packages\ford\fortran_project.py", line 90, in __init__
    ford.sourceform.FortranSourceFile(os.path.join(curdir,item),settings, preprocessor, ext in self.fixed_extensions,incl_src=html_incl_src))
  File "\anaconda3\lib\site-packages\ford\sourceform.py", line 1052, in __init__
    FortranContainer.__init__(self,source,"")
  File "\anaconda3\lib\site-packages\ford\sourceform.py", line 647, in __init__
    self.MODULE_RE.match(line),self))
  File "\anaconda3\lib\site-packages\ford\sourceform.py", line 757, in __init__
    permission,self))
  File "\anaconda3\lib\site-packages\ford\sourceform.py", line 2272, in line_to_variables
    initial = initial[0:search_from] + QUOTES_RE.sub(string,initial[search_from:],count=1)
  File "\anaconda3\lib\re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "\anaconda3\lib\re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "\anaconda3\lib\sre_parse.py", line 1024, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \O at position 1
```

This is on Windows with the latest ford installed via pip. Python 3.7.3.

**Comment by jacobwilliams** [comment]
Problem is in `sourceform.py` I think:

```python
                old_string = NBSP_RE.sub('&nbsp;',parent.strings[num])
                string = ''
                for i in range(len(old_string)):
                    if old_string[i] == "\\" and (old_string[i+1] in '0123456789' or
                                                   old_string[i+1] == 'g'):
                        string += r'\\'
                    elif old_string[i] == '(' and old_string[i+1] =='?':
                        string += r'\('
                    else:
                        string += old_string[i]
                initial = initial[0:search_from] + QUOTES_RE.sub(string,initial[search_from:],count=1)
```

There are several other problems here. Consider this example:

```fortran
module test_module

implicit none

private

character(len=*),parameter,public:: b_ = '(?)'  ! writes `\(?)`
character(len=*),parameter,public:: a  = '\a'   ! write a blank string
character(len=*),parameter,public:: b  = '\b'   ! writes a blank string
character(len=*),parameter,public:: c  = '\c'   ! crashes

end module test_module
```

I'm wondering if we can replace the whole thing with this:

```python
                string = NBSP_RE.sub('&nbsp;',parent.strings[num])
                string = string.replace('\\','\\\\')
                initial = initial[0:search_from] + QUOTES_RE.sub(string,initial[search_from:],count=1)
```

That prints all the strings correctly for the example above.
