### ISSUE TITLE
`sort: type-alpha` fails

### ISSUE THREAD

**Issue by zbeekman** [Fortran-FOSS-Programmers/ford#303]
Here is the debug output:

```
Correlating information from different parts of your project...
Traceback (most recent call last):
  File "/usr/local/bin/ford", line 11, in <module>
    load_entry_point('FORD==6.0.0', 'console_scripts', 'ford')()
  File "/usr/local/Cellar/ford/6.0.0_1/libexec/lib/python3.7/site-packages/ford/__init__.py", line 391, in run
    main(proj_data,proj_docs,md)
  File "/usr/local/Cellar/ford/6.0.0_1/libexec/lib/python3.7/site-packages/ford/__init__.py", line 352, in main
    project.correlate()
  File "/usr/local/Cellar/ford/6.0.0_1/libexec/lib/python3.7/site-packages/ford/fortran_project.py", line 221, in correlate
    if type(container) != str: container.correlate(self)
  File "/usr/local/Cellar/ford/6.0.0_1/libexec/lib/python3.7/site-packages/ford/sourceform.py", line 911, in correlate
    if dtype in self.types: dtype.correlate(project)
  File "/usr/local/Cellar/ford/6.0.0_1/libexec/lib/python3.7/site-packages/ford/sourceform.py", line 1612, in correlate
    self.sort()
  File "/usr/local/Cellar/ford/6.0.0_1/libexec/lib/python3.7/site-packages/ford/sourceform.py", line 413, in sort
    sort_items(self,self.variables)
  File "/usr/local/Cellar/ford/6.0.0_1/libexec/lib/python3.7/site-packages/ford/sourceform.py", line 2435, in sort_items
    items.sort(key=itype_alpha)
  File "/usr/local/Cellar/ford/6.0.0_1/libexec/lib/python3.7/site-packages/ford/sourceform.py", line 2424, in itype_alpha
    return itype(i) + '-' + i.name
  File "/usr/local/Cellar/ford/6.0.0_1/libexec/lib/python3.7/site-packages/ford/sourceform.py", line 2414, in itype
    retstr = retstr + '-' + i.proto[0]
TypeError: can only concatenate str (not "FortranType") to str
```

It looks like `retstr` or `i.proto[0]` need to be cast to strings.

**Comment by ZedThree** [comment]
I've not been able to reproduce this, so if someone who has encountered this bug can post a reproducer that would be incredibly useful! Even something big is fine, I can debug and cut it down
