### ISSUE TITLE
ford-6.0.0 reports segment fault, while ford-5.0.6 reports IndexError: string index out of range

### ISSUE THREAD

**Issue by lyz0530** [Fortran-FOSS-Programmers/ford#323]
Hi, thanks for the ford.
I need to generate a document of a third-party fortran project, which has nearly 5000 lines.
Either ford-6.0.0 or 5.0.6 can be installed successfully and some small examples have been tested.
However when I process the third-party project, errors occur. 
In ford-6.0.0, segment fault is reported.
In ford-5.0.6, IndexError is reported.
I don't know how to fix it.

`Traceback (most recent call last):
  File ".../.conda/envs/py36/bin/ford", line 8, in <module>
    sys.exit(run())

  File ".../.conda/envs/py36/lib/python3.6/site-packages/ford/__init__.py", line 357, in run
    main(proj_data,proj_docs,md)

  File ".../.conda/envs/py36/lib/python3.6/site-packages/ford/__init__.py", line 310, in main
    project = ford.fortran_project.Project(proj_data)

  File ".../.conda/envs/py36/lib/python3.6/site-packages/ford/fortran_project.py", line 95, in __init__
    ford.sourceform.FortranSourceFile(os.path.join(curdir,item),settings, preprocessor, ext in self.fixed_extensions))

  File ".../.conda/envs/py36/lib/python3.6/site-packages/ford/sourceform.py", line 1023, in __init__
    FortranContainer.__init__(self,source,"")

  File ".../.conda/envs/py36/lib/python3.6/site-packages/ford/sourceform.py", line 630, in __init__
    self.MODULE_RE.match(line),self))

  File ".../.conda/envs/py36/lib/python3.6/site-packages/ford/sourceform.py", line 655, in __init__
    permission))

  File ".../.conda/envs/py36/lib/python3.6/site-packages/ford/sourceform.py", line 740, in __init__
    permission,self))

  File ".../.conda/envs/py36/lib/python3.6/site-packages/ford/sourceform.py", line 2149, in line_to_variables
    vartype, kind, strlen, proto, rest = parse_type(line,parent.strings,parent.settings)

  File ".../.conda/envs/py36/lib/python3.6/site-packages/ford/sourceform.py", line 2274, in parse_type
    return (vartype, None, args[1], None, rest)

IndexError: string index out of range
`

**Comment by ZedThree** [comment]
Hi @lyz0530, please could you try with the latest version of Ford, 6.1.1?
