### ISSUE TITLE
Fails with TypeError for preprocessing file

### ISSUE THREAD

**Issue by awvwgk** [Fortran-FOSS-Programmers/ford#380]
Testing Ford 6.1.7 with Python 3.10 (also tested with 3.8 and 3.9) on https://github.com/grimme-lab/mctc-lib/commit/9e2ebec95715c8b4eea45fe4eb617f367c83c28a fails with

```
❯ ford docs.md
Reading file src/mctc/env.f90
Reading file src/mctc/version.F90
Traceback (most recent call last):
  File "/home/awvwgk/software/opt/conda/envs/ford/bin/ford", line 10, in <module>
    sys.exit(run())
  File "/home/awvwgk/software/opt/conda/envs/ford/lib/python3.10/site-packages/ford/__init__.py", line 634, in run
    main(proj_data, proj_docs, md)
  File "/home/awvwgk/software/opt/conda/envs/ford/lib/python3.10/site-packages/ford/__init__.py", line 557, in main
    project = ford.fortran_project.Project(proj_data)
  File "/home/awvwgk/software/opt/conda/envs/ford/lib/python3.10/site-packages/ford/fortran_project.py", line 104, in __init__
    ford.sourceform.FortranSourceFile(
  File "/home/awvwgk/software/opt/conda/envs/ford/lib/python3.10/site-packages/ford/sourceform.py", line 1413, in __init__
    source = ford.reader.FortranReader(
  File "/home/awvwgk/software/opt/conda/envs/ford/lib/python3.10/site-packages/ford/reader.py", line 136, in __init__
    preprocessor = preprocessor + macros + incdirs + [filename]
TypeError: can only concatenate str (not "list") to str
```

Same project file works without problem using Ford 6.1.6.

<details><summary>Environment</summary>

```
❯ mamba list
# packages in environment at /home/awvwgk/software/opt/conda/envs/ford:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
atk-1.0                   2.36.0               h3371d22_4    conda-forge
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cairo                     1.16.0            ha00ac49_1009    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
expat                     2.4.4                h9c3ff4c_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.94              ha180cfb_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
ford                      6.1.7              pyhd8ed1ab_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
gdk-pixbuf                2.42.6               h04a7f16_0    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
graphviz                  2.50.0               h8e749b2_2    conda-forge
gtk2                      2.24.33              h90689f9_2    conda-forge
gts                       0.7.6                h64030ff_2    conda-forge
harfbuzz                  3.2.0                hb4a5f5f_0    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
importlib-metadata        4.10.1          py310hff52083_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h7f98852_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libdeflate                1.8                  h7f98852_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_12    conda-forge
libgd                     2.3.3                h3cfcdeb_1    conda-forge
libglib                   2.70.2               h174f98d_1    conda-forge
libgomp                   11.2.0              h1d223b6_12    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
librsvg                   2.52.5               h0a9e6e8_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_12    conda-forge
libtiff                   4.3.0                h6f004c6_2    conda-forge
libtool                   2.4.6             h9c3ff4c_1008    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markdown                  3.3.6              pyhd8ed1ab_0    conda-forge
markdown-include          0.6.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1           py310h6acc77f_1    conda-forge
md-environ                0.1.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
openssl                   3.0.0                h7f98852_2    conda-forge
pango                     1.50.3               h9967ed3_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pip                       22.0.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
python                    3.10.2          hc74c709_2_cpython    conda-forge
python-graphviz           0.19.1             pyhaef67bd_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                60.6.0          py310hff52083_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
toposort                  1.7                pyhd8ed1ab_0    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zipp                      3.7.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
❯ mamba info

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.19.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


     active environment : ford
    active env location : /home/awvwgk/software/opt/conda/envs/ford
            shell level : 2
       user config file : /home/awvwgk/.condarc
 populated config files : /home/awvwgk/software/opt/conda/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.9.final.0
       virtual packages : __linux=5.10.89=0
                          __glibc=2.33=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/awvwgk/software/opt/conda  (writable)
      conda av data dir : /home/awvwgk/software/opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/awvwgk/software/opt/conda/pkgs
                          /home/awvwgk/.conda/pkgs
       envs directories : /home/awvwgk/software/opt/conda/envs
                          /home/awvwgk/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.9 Linux/5.10.89-1-MANJARO manjaro/21.2.1 glibc/2.33
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by ZedThree** [comment]
Thanks @awvwgk ! I've got a fix, and a better test. I'm just trying to get a decent integrated test and then I'll make a new release

**Comment by ZedThree** [comment]
@awvwgk 6.1.8 is now available
