### ISSUE TITLE
AttributeError: 'FortranType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by awvwgk** [Fortran-FOSS-Programmers/ford#399]
https://github.com/fortran-lang/fpm/blob/main/docs.md fails with Ford version 6.1.9 from PyPI showing the following error message (seems like stdout / stderr are intervened):

```
Traceback (most recent call last):
Reading file src/fpm_sources.f90
  File "/opt/hostedtoolcache/Python/3.10.2/x64/bin/ford", line 8, in <module>
    sys.exit(run())
Reading file src/fpm_strings.f90
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/ford/__init__.py", line 638, in run
Reading file src/fpm_model.f90
    main(proj_data, proj_docs, md)
Reading file src/fpm_source_parsing.f90
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/ford/__init__.py", line 585, in main
Reading file src/fpm_environment.f90
    project.correlate()
Reading file src/fpm_filesystem.F90
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/ford/fortran_project.py", line 263, in correlate
Preprocessing /home/runner/work/fpm/fpm/src/fpm_filesystem.F90
    container.correlate(self)
Reading file src/fpm_backend.F90
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/ford/sourceform.py", line 1223, in correlate
Preprocessing /home/runner/work/fpm/fpm/src/fpm_backend.F90
    func.correlate(project)
Reading file src/fpm_targets.f90
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/ford/sourceform.py", line 1231, in correlate
Reading file src/fpm_compiler.f90
    var.correlate(project)
Reading file src/fpm_backend_output.f90
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/ford/sourceform.py", line 2217, in correlate
Reading file src/fpm_os.F90
    if self.proto[0].lower() in self.parent.all_types:
Preprocessing /home/runner/work/fpm/fpm/src/fpm_os.F90
AttributeError: 'FortranType' object has no attribute 'lower'
```

**Comment by ZedThree** [comment]
Thanks for the bug report @awvwgk ! I've fixed this and expanded the test suite :)

**Comment by awvwgk** [comment]
Thanks for the swift release, I'll skip 6.1.9 on conda-forge and directly package 6.1.10 (see https://github.com/conda-forge/ford-feedstock/pull/5)
