### ISSUE TITLE
ModuleNotFoundError with a fresh pip install of Ford

### ISSUE THREAD

**Issue by szaghi** [Fortran-FOSS-Programmers/ford#432]
Dear all,

I am facing with the following error:

```bash
Traceback (most recent call last):
  File "/home/stefano/.local/bin/ford", line 8, in <module>
    sys.exit(run())
  File "/home/stefano/.local/lib/python3.10/site-packages/ford/__init__.py", line 633, in run
    proj_data, proj_docs, md = initialize()
  File "/home/stefano/.local/lib/python3.10/site-packages/ford/__init__.py", line 236, in initialize
    return parse_arguments(vars(args), proj_docs, directory)
  File "/home/stefano/.local/lib/python3.10/site-packages/ford/__init__.py", line 406, in parse_arguments
    md = markdown.Markdown(
  File "/home/stefano/.local/lib/python3.10/site-packages/markdown/core.py", line 96, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "/home/stefano/.local/lib/python3.10/site-packages/markdown/core.py", line 123, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/home/stefano/.local/lib/python3.10/site-packages/markdown/core.py", line 162, in build_extension
    module = importlib.import_module(ext_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'markdown.extensions.toc(anchorlink=True)'
```
Ford is freshly installed by means of 

```bash
pip install ford
Requirement already satisfied: markdown in /home/stefano/.local/lib/python3.10/site-packages (from ford) (3.3.7)
Requirement already satisfied: tqdm in /home/stefano/.local/lib/python3.10/site-packages (from ford) (4.64.0)
Requirement already satisfied: jinja2>=2.1 in /usr/lib/python3/dist-packages (from ford) (3.0.3)
Requirement already satisfied: markdown-include>=0.5.1 in /home/stefano/.local/lib/python3.10/site-packages (from ford) (0.6.0)
Requirement already satisfied: graphviz in /home/stefano/.local/lib/python3.10/site-packages (from ford) (0.20)
Requirement already satisfied: beautifulsoup4>=4.5.1 in /usr/lib/python3/dist-packages (from ford) (4.10.0)
Requirement already satisfied: python-markdown-math~=0.8 in /home/stefano/.local/lib/python3.10/site-packages (from ford) (0.8)
Requirement already satisfied: toposort in /home/stefano/.local/lib/python3.10/site-packages (from ford) (1.7)
Requirement already satisfied: pygments in /usr/lib/python3/dist-packages (from ford) (2.11.2)
Installing collected packages: ford
Successfully installed ford-6.1.12
```
The system is a Pop!_OS 22.04 (ubuntu derivated) with Python 3.10.4, but the same identical error is gotten on github actions (ubuntu-latest runner). Probably, I am doing something wrong with the installation. 

I am using Ford to build the doc of https://github.com/szaghi/FLAP as I was used to doing until the past year.

Do you have any suggestions?

Kind regards,
Stefano

**Comment by ZedThree** [comment]
Looking at the project file for FLAP:

```
md_extensions: markdown.extensions.toc(anchorlink=True)
               markdown.extensions.smarty(smart_quotes=False)
               markdown.extensions.extra
               markdown_checklist.extension
```

This syntax is wrong: `markdown.extensions.toc(anchorlink=True)`. We pass this list of markdown extensions to `markdown`, which tries to `import` them, so they must be valid targets for `import`. Maybe previously you were using an earlier version of `markdown`?

Ford doesn't currently support passing any configs to extensions, which is what you're trying to do here, but this is possible in principle.

**Comment by szaghi** [comment]
@ZedThree Thank you for the quick support, yes, in the past Ford supports this config. I am going to re-write my Ford configuration.

Kind regards
