### ISSUE TITLE
Ford fails with yaFyaml

### ISSUE THREAD

**Issue by mathomp4** [Fortran-FOSS-Programmers/ford#469]
Recently, as a test, I decided to try Ford on (some of) the GFE libraries of @tclune. Namely the ones that are Fortran-filled:

* [pFUnit](https://github.com/Goddard-Fortran-Ecosystem/pFUnit)
* [fArgParse](https://github.com/Goddard-Fortran-Ecosystem/fArgParse)
* [pFlogger](https://github.com/Goddard-Fortran-Ecosystem/pFlogger)
* [yaFyaml](https://github.com/Goddard-Fortran-Ecosystem/yaFyaml)

I've been able to get the first three to work just fine (pointing to the right `include/` dir, adding an install of `gFTL`, etc.) but yaFyaml fails:
```
❯ ford docs.yaFyaml.md
Reading file ../src/AbstractStream.F90
Preprocessing /Users/mathomp4/Ford-Testing/yaFyaml/Ford/../src/AbstractStream.F90
Reading file ../src/AbstractFile.F90
Preprocessing /Users/mathomp4/Ford-Testing/yaFyaml/Ford/../src/AbstractFile.F90
Reading file ../src/yafyaml.F90
Preprocessing /Users/mathomp4/Ford-Testing/yaFyaml/Ford/../src/yafyaml.F90
...
Reading file ../src/Nodes/YAML_Node.F90
Preprocessing /Users/mathomp4/Ford-Testing/yaFyaml/Ford/../src/Nodes/YAML_Node.F90

Processing documentation comments...
Correlating information from different parts of your project...

Creating HTML documentation...
Writing documentation to '/Users/mathomp4/Ford-Testing/yaFyaml/Ford/doc'...
Error rendering page '/Users/mathomp4/Ford-Testing/yaFyaml/Ford/doc/type/abstractstream.html'
Traceback (most recent call last):
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/ford/output.py", line 290, in html
    return self.render(self.data, self.proj, self.obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/ford/output.py", line 424, in render
    return template.render(data, project=project, **{self.payload_key: object})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/ford/templates/type_page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/ford/templates/base.html", line 151, in top-level template code
    {% block body %}
^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/ford/templates/type_page.html", line 92, in block 'body'
    {{ macros.bound_info(bp) }}
^^^^^^^^^^^^^^^^^^^
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/ford/templates/macros.html", line 351, in template
    {{ binding_summary(bind) }}
^^^^^^^^^^^^^^^
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/ford/templates/macros.html", line 284, in template
    {{ proc_line(proc, proto=proto) }}
^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/ford/templates/macros.html", line 428, in template
    {{ deprecated(proc) }}
  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/ford/templates/macros.html", line 156, in template
    {%- if entity.meta['deprecated'] -%}
  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/jinja2/environment.py", line 466, in getitem
    return obj[argument]
           ~~~^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'meta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mathomp4/.homebrew/brew/bin/ford", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/ford/__init__.py", line 648, in run
    main(proj_data, proj_docs, md)
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/ford/__init__.py", line 633, in main
    docs.writeout()
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/ford/output.py", line 261, in writeout
    p.writeout()
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/ford/output.py", line 298, in writeout
    out.write(self.html.encode("utf8"))
              ^^^^^^^^^
  File "/Users/mathomp4/.homebrew/brew/Cellar/ford/6.1.17/libexec/lib/python3.11/site-packages/ford/output.py", line 292, in html
    raise RuntimeError(
RuntimeError: Error rendering 'abstractstream.html' for 'AbstractStream' : 'str object' has no attribute 'meta'
```

So, yeah. This is a bit beyond me. The [file it seems to be having issues with](https://github.com/Goddard-Fortran-Ecosystem/yaFyaml/blob/main/src/AbstractStream.F90) isn't too exciting, but maybe something in it is triggering a fault?

**Comment by ZedThree** [comment]
Thanks for the bug report @mathomp4 ! It looks like it doesn't like the type for some reason.

I just stuck that module into godbolt, and it has [some errors](https://godbolt.org/z/69YT8nGfx). 

Fixing the errors:

```fortran
module fy_AbstractStream
  private

  public :: AbstractStream

  type, abstract :: AbstractStream
     private
     character(:), allocatable :: buffer
   contains
     procedure(read), deferred :: read_
  end type AbstractStream


  abstract interface

     function read(this, n_characters) result(buffer)
       import AbstractStream
       character(:), allocatable :: buffer
       class(AbstractStream), intent(inout) :: this
       integer, optional, intent(in) :: n_characters
     end function read

  end interface

end module fy_AbstractStream
```

and it compiles on godbolt, and Ford seems to process it correctly.

**Comment by mathomp4** [comment]
@ZedThree How very odd. The bug is obvious now that I see it, and yet we use this code with GCC 12.2 and I've compiled it for sure! 

Well, time to fix it up!

**Comment by mathomp4** [comment]
Confirmed it's all good if I exclude that file. Thanks!
