### ISSUE TITLE
Issue with FortranSubmoduleProcedure

### ISSUE THREAD

**Issue by khaors** [Fortran-FOSS-Programmers/ford#478]
Hello:

I have installed ford via conda in my new machine. When I tried to create the documentation I got this error: 

```
Processing documentation comments...
Correlating information from different parts of your project...
Traceback (most recent call last):
  File "C:\Users\Oscar\.conda\envs\FORD\Scripts\ford-script.py", line 9, in <module>
    sys.exit(run())
             ^^^^^
  File "C:\Users\Oscar\.conda\envs\FORD\Lib\site-packages\ford\__init__.py", line 645, in run
    main(proj_data, proj_docs, md)
  File "C:\Users\Oscar\.conda\envs\FORD\Lib\site-packages\ford\__init__.py", line 592, in main
    project.correlate()
  File "C:\Users\Oscar\.conda\envs\FORD\Lib\site-packages\ford\fortran_project.py", line 254, in correlate
    container.correlate(self)
  File "C:\Users\Oscar\.conda\envs\FORD\Lib\site-packages\ford\sourceform.py", line 1091, in correlate
    if proc.module and proc.name.lower() in self.all_procs:
       ^^^^^^^^^^^
AttributeError: 'FortranSubmoduleProcedure' object has no attribute 'module'
```

**Comment by ZedThree** [comment]
Hi @khaors, thanks for the bug report! Are you able to share the source that Ford is failing on? Even better would be if you could give us a  cut down snippet that shows this.

**Comment by ZedThree** [comment]
Closed as stale -- feel free to reopen if there's still an issue
