### ISSUE TITLE
Failure to Create Graph

### ISSUE THREAD

**Issue by JulesKouatchou** [Fortran-FOSS-Programmers/ford#501]
I am am using FORD to create documentation of a large Fortran application. When I set "graph: false" in the FORD project file, I get the error message below. I am wondering if you can help me identify the source of the problem. I am willing to share with you the source code (tarball of about 12 Mb).

Thanks.

Jules

---------------------------------------------------------

Processing documentation comments...
Correlating information from different parts of your project...

Creating HTML documentation...
Generating graphs: 100%|███████████████████████████████████████████████████████████████████████| 2785/2785 [24:24<00:00,  1.90/s]
Writing documentation to '/Users/jkouatch/myTasks/GEOS_Documentation/MAPL/Ford/doc'...
Traceback (most recent call last):
  File "/Users/jkouatch/anaconda3/lib/python3.8/site-packages/ford/output.py", line 285, in html
    return self.render(self.data, self.proj, self.obj)
  File "/Users/jkouatch/anaconda3/lib/python3.8/site-packages/ford/output.py", line 419, in render
    return template.render(data, project=project, **{self.payload_key: object})
  File "/Users/jkouatch/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/jkouatch/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/jkouatch/anaconda3/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/jkouatch/anaconda3/lib/python3.8/site-packages/ford/templates/proc_page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/jkouatch/anaconda3/lib/python3.8/site-packages/ford/templates/base.html", line 178, in top-level template code
    {% block body %}
  File "/Users/jkouatch/anaconda3/lib/python3.8/site-packages/ford/templates/proc_page.html", line 43, in block "body"
    {% if procedure.calledbygraph or procedure.callsgraph %}
  File "/Users/jkouatch/anaconda3/lib/python3.8/site-packages/ford/graphs.py", line 897, in __bool__
    return bool(self.__str__())
  File "/Users/jkouatch/anaconda3/lib/python3.8/site-packages/ford/graphs.py", line 824, in __str__
    if self.hop_edges[0][0].ident == self.root[0].ident:
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jkouatch/anaconda3/bin/ford", line 8, in <module>
    sys.exit(run())
  File "/Users/jkouatch/anaconda3/lib/python3.8/site-packages/ford/__init__.py", line 646, in run
    main(proj_data, proj_docs, md)
  File "/Users/jkouatch/anaconda3/lib/python3.8/site-packages/ford/__init__.py", line 631, in main
    docs.writeout()
  File "/Users/jkouatch/anaconda3/lib/python3.8/site-packages/ford/output.py", line 256, in writeout
    p.writeout()
  File "/Users/jkouatch/anaconda3/lib/python3.8/site-packages/ford/output.py", line 293, in writeout
    out.write(self.html.encode("utf8"))
  File "/Users/jkouatch/anaconda3/lib/python3.8/site-packages/ford/output.py", line 287, in html
    raise RuntimeError(
RuntimeError: Error rendering 'mapl_verify.html' for 'MAPL_Verify' : 0

**Comment by ZedThree** [comment]
That is a bit surprising that it still tries to generate the graphs! What version of Ford are you using? If you can share the code, it would help tracking down the bug.

**Comment by JulesKouatchou** [comment]
I am using Ford 6.2.2.

**Comment by JulesKouatchou** [comment]
Thank you for fixing the problem. I assume that you created a new version of FORD. Can you let me know which one so that I can test it?

Thanks.

**Comment by ZedThree** [comment]
Yes, just released as 6.2.4, should be available to download in a few minutes

**Comment by JulesKouatchou** [comment]
I updated FORD to version 6.2.4 and I was able to generate the graphs. Thank you for your assistance.
