### ISSUE TITLE
How to use the `externalize` option?

### ISSUE THREAD

**Issue by mgoonde** [Fortran-FOSS-Programmers/ford#676]
Hello,
I have a code with a plugin system, where the base code's documentation is written by FORD, but the plugin documentations are separate ford projects not included in the base. I would like to use the `externalize` option on the base code, to be able to reference it from the documentation of the plugins (also written by FORD).

I tried setting `externalize: true` in the base code, and then giving `external: local=/path/to/base/doc` in the project file of a plugin documentation. But upon running FORD for my plugin, i get the error:
```
  Correlating information from different parts of your project...
Traceback (most recent call last):
  File "/home/mgunde/.local/bin/ford", line 8, in <module>
    sys.exit(run())
  File "/home/mgunde/.local/lib/python3.10/site-packages/ford/__init__.py", line 489, in run
    main(proj_data, proj_docs)
  File "/home/mgunde/.local/lib/python3.10/site-packages/ford/__init__.py", line 420, in main
    project.correlate()
  File "/home/mgunde/.local/lib/python3.10/site-packages/ford/fortran_project.py", line 340, in correlate
    container.correlate(self)
  File "/home/mgunde/.local/lib/python3.10/site-packages/ford/sourceform.py", line 1273, in correlate
    dtype.correlate(project)
  File "/home/mgunde/.local/lib/python3.10/site-packages/ford/sourceform.py", line 2069, in correlate
    proc.correlate(project)
  File "/home/mgunde/.local/lib/python3.10/site-packages/ford/sourceform.py", line 2485, in correlate
    if self.proto:
AttributeError: 'ExternalBoundProcedure' object has no attribute 'proto'
```

Without the `external: local=...` specification, the documentation writes normally (however giving warnings that references are not found, which is normal i guess).

Is this an error due to my wrong use of the `external` option, or something else?

thanks

**Comment by haraldkl** [comment]
It sounds to me like you are using it as intended.

It may be that the externalize function does not properly deal with type-bound procedures. I guess, those are not tested in that setting.

**Comment by haraldkl** [comment]
The [test for external projects](https://github.com/Fortran-FOSS-Programmers/ford/blob/master/test_data/external_project/external_project/src/external.f90) *does* contain a type bound procedure:

```
  type, abstract, public :: solverAborts_type
  contains
    procedure(load_aborts), deferred :: load
  end type solverAborts_type
```

Can you share some sample code that causes the error?

**Comment by haraldkl** [comment]
Does #677  help?

**Comment by mgoonde** [comment]
> Does #677 help?

It does not.

**Comment by haraldkl** [comment]
Thanks! I can reproduce the bug and will have a look.

**Comment by haraldkl** [comment]
I've now pushed some changes to #677, which makes it work for me. Can you please give it a try?

**Comment by mgoonde** [comment]
Yeah that seems to work. Awesome, thanks!

There seems to be some small inconsistency however, in that the directory specified in ` external: local=...` seems relative to the location from which i launch FORD, while for comparison the `output_dir=....` seems relative to the location of the ford project file.

**Comment by haraldkl** [comment]
In 6fe3fb2d216c5f21d20e3816ff92d58d74f5a04a I now changed the external definition to be relative to the project directory (if it is relative).

**Comment by mgoonde** [comment]
That seems to work for me.

Is it possible to have several paths for the `external: local=....` command?

Also, is it desirable to have a hard-stop error when the needed file `modules.json` is not found? Could it just print a warning and continue without it?

**Comment by haraldkl** [comment]
This should work with:

```
ford -L 'local = /path'
```

**Comment by haraldkl** [comment]
This may depend on the extend of what to add to the search. The search iterates over the generated pages and adds them to the search. Adding all pages from the subprojects into the search appears a little counterproductive to me. I guess it would be possible to iterate over all Fortran objects that have an `external_url` attribute, to add them to the search additionally, but the question then is what needs to be added as searched text for them.

**Comment by mgoonde** [comment]
I'm not really sure how this works, but if the search index is generated in a subproject, it could be added to the search of the project which references it as `external`, since it's already generated in a file anyway. So kind of multiple search index files. If that is possible.

**Comment by ZedThree** [comment]
Fixed in #677
